server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true

weather:
  expiry-mins: 60

open-weather-map:
  api:
    url: http://api.openweathermap.org
    key:

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.vanguard.weatherapp: INFO

